[package]
name = "archivindex-wbm-cdx-index"
authors = { workspace = true }
repository = { workspace = true }
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
archivindex-wbm = { path = "../wbm/" }
chrono = { workspace = true }
rocksdb = { workspace = true }
thiserror = { workspace = true }
