[package]
name = "archivindex-wbm-cas"
description = "Content-addressable storage for Wayback Machine snapshot data"
keywords = ["wayback-machine", "web-archive", "content-addressable"]
categories = ["filesystem"]
authors = { workspace = true }
repository = { workspace = true }
version = { workspace = true }
exclude = ["tests/"]
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
readme = { workspace = true }

[lints]
workspace = true

[features]
default = ["zstd"]
zstd = ["dep:zstd"]

[dependencies]
archivindex-wbm = { version = "0.1.0", path = "../wbm/" }
bytes = { workspace = true }
flate2 = { workspace = true }
log = { workspace = true }
prefix-file-tree = { workspace = true }
thiserror = { workspace = true }
zstd = { workspace = true, optional = true }

[dev-dependencies]
tempfile = { workspace = true }
