[package]
name = "archivindex-wbm-cdx-index-cli"
authors.workspace = true
repository.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[[bin]]
name = "archivindex-wbm-cdx-index"
path = "src/main.rs"
# Avoid a rustdoc output-filename collision with the `archivindex-wbm-cdx-index` library crate.
doc = false

[dependencies]
anyhow.workspace = true
archivindex-cli-support.workspace = true
archivindex-wbm.workspace = true
archivindex-wbm-cdx-index.workspace = true
archivindex-wbm-json.workspace = true
clap.workspace = true
csv.workspace = true
indicatif.workspace = true
log.workspace = true
serde_json.workspace = true
zstd.workspace = true

[dev-dependencies]
tempfile.workspace = true
