[package]
name = "archivindex-wxj-cli"
authors = { workspace = true }
repository = { workspace = true }
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
archivindex-wbm = { path = "../wbm/" }
archivindex-wbm-cas = { path = "../wbm-cas/" }
archivindex-wxj = { path = "../wxj/" }
birdsite = { workspace = true }
chrono = { workspace = true }
cli-helpers = { workspace = true }
csv = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha1 = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
zstd = { workspace = true }
