[package]
name = "archivindex-hacks"
workspace = ".."
version.workspace = true
authors.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
archivindex-wbm = { path = "../wbm/" }
archivindex-wbm-downloader = { path = "../wbm-downloader/" }
archivindex-wbm-json = { path = "../wbm-json/" }
bounded-static = { workspace = true }
chrono = { workspace = true }
cli-helpers = { workspace = true }
csv = { workspace = true }
futures = { workspace = true }
globwalk = "0.9"
serde = { workspace = true }
serde_json = { workspace = true, features = ["raw_value"] }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
walkdir = "2"
zstd = { workspace = true }
