[package]
name = "archivindex-wbm-json"
description = "Compact NDJSON snapshot files for JSON content archived by the Wayback Machine"
keywords = ["wayback-machine", "web-archive", "ndjson"]
categories = ["parser-implementations", "encoding"]
authors = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
version = { workspace = true }

[dependencies]
archivindex-wbm = { version = "0.1.0", path = "../wbm/" }
archivindex-wbm-invalid-log = { version = "0.1.0", path = "../wbm-invalid-log/" }
bounded-static = { workspace = true }
cel = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
regex = { workspace = true }
rusqlite = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha1 = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
zstd = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
