[package]
name = "archivindex-wbm-downloader-cli"
authors = { workspace = true }
repository = { workspace = true }
version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
publish = false

[lints]
workspace = true

[[bin]]
name = "archivindex-wbm-downloader"
path = "src/main.rs"
# Avoid a rustdoc output-filename collision with the `archivindex-wbm-downloader` library crate.
doc = false

[dependencies]
anyhow = { workspace = true }
archivindex-cli-support = { workspace = true }
archivindex-wbm = { path = "../wbm/" }
archivindex-wbm-cas = { path = "../cas/" }
archivindex-wbm-downloader = { path = "../downloader/" }
archivindex-wbm-invalid-log = { path = "../invalid-log/" }
bounded-static = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
csv = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
