[package]
name = "archivindex-wbm-downloader-cli"
authors = { workspace = true }
repository = { workspace = true }
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[[bin]]
name = "archivindex-wbm-downloader"
path = "src/main.rs"

[dependencies]
archivindex-wbm = { path = "../wbm/" }
archivindex-wbm-cas = { path = "../wbm-cas/" }
archivindex-wbm-downloader = { path = "../wbm-downloader/" }
archivindex-wbm-invalid-log = { path = "../wbm-invalid-log/" }
chrono = { workspace = true }
cli-helpers = { workspace = true }
csv = { workspace = true }
rusqlite = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
