[package]
name = "archivindex-wbm-cdx-index-cli"
authors = { workspace = true }
repository = { workspace = true }
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[[bin]]
name = "archivindex-wbm-cdx-index"
path = "src/main.rs"

[dependencies]
archivindex-wbm = { path = "../wbm/" }
archivindex-wbm-cdx-index = { path = "../wbm-cdx-index/" }
archivindex-wbm-json = { path = "../wbm-json/" }
cli-helpers = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
zstd = { workspace = true }
