[package]
name = "archivindex-wbm"
authors = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
version = { workspace = true }

[features]
default = ["sqlite", "validation"]
sqlite = ["dep:rusqlite"]
validation = []

[dependencies]
bounded-static = { workspace = true }
chrono = { workspace = true }
data-encoding = { workspace = true }
digest-io = { workspace = true }
http = { workspace = true }
regex = { workspace = true }
rusqlite = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha1 = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }

[dev-dependencies]
quickcheck = { workspace = true }
quickcheck_macros = "1"
